import '../app/globals.css'

export const metadata = {
  title: 'Ecommerce Website',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='text-black font-display'>{children}</body>
    </html>
  )
}
